server:
  port: 8080
spring:
  application:
    name: yunxiutongDispatchSystem
  profiles:
    active: dev
  datasource:
    driver-class-name: ${YXT.datasource.driver-class-name}
    username: ${YXT.datasource.username}
    password: ${YXT.datasource.password}
    url:  jdbc:mysql://${YXT.datasource.host}:${YXT.datasource.port}/${YXT.datasource.database}??serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
mybatis:
  configuration:
    #??????
    map-underscore-to-camel-case: true
  #????
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.entity

logging:
  level:
    org:
      example:
        mapper: debug
        service:  info
        controller: info

